#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Reflection;
using System.Runtime.Serialization;


namespace BHS.UWT.TPM.Data
{	
      public partial class SHIPMENT_HEADER
      {
               
            public decimal INTERNAL_SHIPMENT_NUM { get; set; }
            public string warehouse { get; set; }
            public decimal? SHIPPING_LOAD_NUM { get; set; }
            public string SHIPMENT_ID { get; set; }
            public string LAUNCH_STEP { get; set; }
            public decimal TRAILING_STS { get; set; }
            public DateTime? TRAILING_STS_DATE { get; set; }
            public char TRAILING_STS_FAILED { get; set; }
            public string ORDER_TYPE { get; set; }
            public char CONSOLIDATED { get; set; }
            public decimal LEADING_STS { get; set; }
            public DateTime? LEADING_STS_DATE { get; set; }
            public string CARRIER { get; set; }
            public char LEADING_STS_FAILED { get; set; }
            public string COMPANY { get; set; }
            public string CARRIER_SERVICE { get; set; }
            public string CARRIER_GROUP { get; set; }
            public string CARRIER_TYPE { get; set; }
            public string FREIGHT_TERMS { get; set; }
            public string LIABILITY_TERMS { get; set; }
            public string CUSTOMER { get; set; }
            public string SHIP_TO { get; set; }
            public string ROUTE { get; set; }
            public string STOP { get; set; }
            public string SHIP_TO_ADDRESS1 { get; set; }
            public string CUSTOMER_NAME { get; set; }
            public string SHIP_TO_ADDRESS2 { get; set; }
            public string SHIP_TO_ADDRESS3 { get; set; }
            public string SHIP_TO_CITY { get; set; }
            public string SHIP_TO_STATE { get; set; }
            public string SHIP_TO_COUNTRY { get; set; }
            public string SHIP_TO_POSTAL_CODE { get; set; }
            public string SHIP_TO_PHONE_NUM { get; set; }
            public string SHIP_TO_FAX_NUM { get; set; }
            public string CUSTOMER_ADDRESS1 { get; set; }
            public decimal? LAUNCH_NUM { get; set; }
            public string WEIGHT_UM { get; set; }
            public string VOLUME_UM { get; set; }
            public string ROUTING_CODE { get; set; }
            public char? SINGLE_ITEM_CARTONS { get; set; }
            public string USER_DEF1 { get; set; }
            public string USER_DEF2 { get; set; }
            public decimal? PRIORITY { get; set; }
            public string USER_DEF3 { get; set; }
            public string USER_DEF4 { get; set; }
            public string USER_DEF5 { get; set; }
            public string USER_DEF6 { get; set; }
            public decimal? USER_DEF7 { get; set; }
            public char? MANUALLY_ENTERED { get; set; }
            public decimal? USER_DEF8 { get; set; }
            public string USER_STAMP { get; set; }
            public string PROCESS_STAMP { get; set; }
            public DateTime DATE_TIME_STAMP { get; set; }
            public string BOL_NUM_ALPHA { get; set; }
            public string PRO_NUM_ALPHA { get; set; }
            public string CUSTOMER_ADDRESS3 { get; set; }
            public string CUSTOMER_ADDRESS2 { get; set; }
            public string CUSTOMER_ATTENTION_TO { get; set; }
            public string CUSTOMER_CITY { get; set; }
            public string CUSTOMER_STATE { get; set; }
            public string CUSTOMER_COUNTRY { get; set; }
            public string CUSTOMER_POSTAL_CODE { get; set; }
            public string CUSTOMER_PHONE_NUM { get; set; }
            public string CUSTOMER_FAX_NUM { get; set; }
            public string CUSTOMER_EMAIL_ADDRESS { get; set; }
            public string SHIP_TO_NAME { get; set; }
            public string SHIP_TO_ATTENTION_TO { get; set; }
            public string SHIP_TO_EMAIL_ADDRESS { get; set; }
            public DateTime? REQUESTED_DELIVERY_DATE { get; set; }
            public string REQUESTED_DELIVERY_TYPE { get; set; }
            public DateTime SCHEDULED_SHIP_DATE { get; set; }
            public DateTime? PLANNED_SHIP_DATE { get; set; }
            public DateTime? ACTUAL_SHIP_DATE_TIME { get; set; }
            public DateTime? PLANNED_DELIVERY_DATE_TIME { get; set; }
            public DateTime? ACTUAL_DELIVERY_DATE_TIME { get; set; }
            public string QUANTITY_UM { get; set; }
            public decimal? TOTAL_FREIGHT_CHARGE { get; set; }
            public decimal? BASE_FREIGHT_CHARGE { get; set; }
            public decimal? FREIGHT_DISCOUNT { get; set; }
            public decimal? ACCESSORIAL_CHARGE { get; set; }
            public char CONSOLIDATION_ALLOWED { get; set; }
            public string INTERMEDIATE_CONSIGNEE { get; set; }
            public string INTERMEDIATE_NAME { get; set; }
            public string INTERMEDIATE_ADDRESS1 { get; set; }
            public string INTERMEDIATE_ADDRESS2 { get; set; }
            public string INTERMEDIATE_ADDRESS3 { get; set; }
            public string INTERMEDIATE_ATTENTION_TO { get; set; }
            public string INTERMEDIATE_CITY { get; set; }
            public string INTERMEDIATE_STATE { get; set; }
            public string INTERMEDIATE_COUNTRY { get; set; }
            public string INTERMEDIATE_POSTAL_CODE { get; set; }
            public string INTERMEDIATE_PHONE_NUM { get; set; }
            public string INTERMEDIATE_FAX_NUM { get; set; }
            public string INTERMEDIATE_EMAIL_ADDRESS { get; set; }
            public string FREIGHT_BILL_TO { get; set; }
            public string FREIGHT_BILL_TO_NAME { get; set; }
            public string FREIGHT_BILL_TO_ADDRESS1 { get; set; }
            public string FREIGHT_BILL_TO_ADDRESS2 { get; set; }
            public string FREIGHT_BILL_TO_ADDRESS3 { get; set; }
            public string FREIGHT_BILL_TO_ATTENTION_TO { get; set; }
            public string FREIGHT_BILL_TO_CITY { get; set; }
            public string FREIGHT_BILL_TO_STATE { get; set; }
            public string FREIGHT_BILL_TO_COUNTRY { get; set; }
            public string FREIGHT_BILL_TO_POSTAL_CODE { get; set; }
            public string FREIGHT_BILL_TO_PHONE_NUM { get; set; }
            public string FREIGHT_BILL_TO_FAX_NUM { get; set; }
            public string FREIGHT_BILL_TO_EMAIL_ADDRESS { get; set; }
            public string ERP_ORDER { get; set; }
            public decimal? INTERNAL_ORDER_NUM { get; set; }
            public string EXPORT_TAX_ID { get; set; }
            public string PARTIES { get; set; }
            public string LOADING_PIER { get; set; }
            public string TRANSPORTATION_MODE { get; set; }
            public string EXPORT_PORT { get; set; }
            public string UNLOADING_PORT { get; set; }
            public char CONTAINERIZED { get; set; }
            public string FTZ { get; set; }
            public string VALIDATED_LICENSE { get; set; }
            public DateTime? LICENSE_EXP_DATE { get; set; }
            public string ECCN { get; set; }
            public string AUTHORIZED_EMPL_NAME { get; set; }
            public string AUTHORIZED_EMPL_TITLE { get; set; }
            public string UPLOAD_INTERFACE_BATCH { get; set; }
            public char? CUSTOMER_RESIDENTIAL_FLAG { get; set; }
            public char? SHIPTO_RESIDENTIAL_FLAG { get; set; }
            public string REJECTION_NOTE { get; set; }
            public string INTERFACE_RECORD_ID { get; set; }
            public string CUSTOMER_CATEGORY1 { get; set; }
            public string CUSTOMER_CATEGORY2 { get; set; }
            public string CUSTOMER_CATEGORY3 { get; set; }
            public string CUSTOMER_CATEGORY4 { get; set; }
            public string CUSTOMER_CATEGORY5 { get; set; }
            public string CUSTOMER_CATEGORY6 { get; set; }
            public string CUSTOMER_CATEGORY7 { get; set; }
            public string CUSTOMER_CATEGORY8 { get; set; }
            public string CUSTOMER_CATEGORY9 { get; set; }
            public string CUSTOMER_CATEGORY10 { get; set; }
            public string CONSOLIDATION_DOCK_LOC_AREA { get; set; }
            public string CONSOLIDATION_DOCK_LOC_POS { get; set; }
            public string PROCESS_TYPE { get; set; }
            public string CREATION_PROCESS_STAMP { get; set; }
            public DateTime? CREATION_DATE_TIME_STAMP { get; set; }
            public string IMMEDIATE_NEEDS_NOTE { get; set; }
            public char ALLOCATE_COMPLETE { get; set; }
            public string ALTERNATE_EMAIL_ADDRESS { get; set; }
            public decimal? STOP_SEQUENCE { get; set; }
            public decimal? INTERNAL_CARRIER_NUM { get; set; }
            public string STORE_DISTRIBUTION { get; set; }
            public decimal? TOTAL_LBR_ESTIMATE { get; set; }
            public decimal? WEIGHT_ENTERED { get; set; }
            public decimal? VOLUME_ENTERED { get; set; }
            public decimal? VALUE_ENTERED { get; set; }
            public char LOCKED { get; set; }
            public string SHIPPER_CODE { get; set; }
      }

      public partial class SYSTEM_CONFIG_DETAIL
      {
               
            public decimal OBJECT_ID { get; set; }
            public string SYS_KEY { get; set; }
            public string DESCRIPTION { get; set; }
            public string SYSTEM_VALUE { get; set; }
            public string RECORD_TYPE { get; set; }
            public string LOOKUP_KEY { get; set; }
            public char SYSTEM_CREATED { get; set; }
            public string USER_DEF1 { get; set; }
            public string USER_DEF2 { get; set; }
            public string USER_DEF3 { get; set; }
            public string USER_DEF4 { get; set; }
            public string USER_DEF5 { get; set; }
            public string USER_DEF6 { get; set; }
            public decimal? USER_DEF7 { get; set; }
            public decimal? USER_DEF8 { get; set; }
            public string USER_STAMP { get; set; }
            public string PROCESS_STAMP { get; set; }
            public DateTime DATE_TIME_STAMP { get; set; }
            public char VALUE_REQUIRED { get; set; }
      }

      public partial class WEB_USER
      {
               
            public string WEB_USER1 { get; set; }
            public string PASSWORD { get; set; }
            public string USER_TYPE { get; set; }
            public string EMAIL_ADDRESS { get; set; }
            public string CUSTOMER_AUTH { get; set; }
            public string COMPANY_AUTH { get; set; }
            public string MARQUEE_MSG { get; set; }
            public string USER_DEF1 { get; set; }
            public string USER_DEF2 { get; set; }
            public string USER_DEF3 { get; set; }
            public string USER_DEF4 { get; set; }
            public string USER_DEF5 { get; set; }
            public string USER_DEF6 { get; set; }
            public decimal? USER_DEF7 { get; set; }
            public decimal? USER_DEF8 { get; set; }
            public string USER_STAMP { get; set; }
            public string PROCESS_STAMP { get; set; }
            public DateTime DATE_TIME_STAMP { get; set; }
            public string CUSTOMER { get; set; }
            public string COMPANY { get; set; }
            public string CUSTOMER_GROUP { get; set; }
            public string VENDOR { get; set; }
            public string DEFAULT_LANGUAGE { get; set; }
            public string SHIP_TO_SELECT_AUTH { get; set; }
            public char ORDER_PROCESSING { get; set; }
            public string ITEM_SELECTION_AUTH { get; set; }
            public char AVAILABILITY_CHECKING { get; set; }
            public char CLICKWRAP_ACCEPTED { get; set; }
      }

      public partial class WEB_USER_COMPANY_ASSIGNMENT
      {
               
            public string COMPANY { get; set; }
            public string WEB_USER { get; set; }
            public string USER_DEF1 { get; set; }
            public string USER_DEF2 { get; set; }
            public string USER_DEF3 { get; set; }
            public string USER_DEF4 { get; set; }
            public string USER_DEF5 { get; set; }
            public string USER_DEF6 { get; set; }
            public decimal? USER_DEF7 { get; set; }
            public decimal? USER_DEF8 { get; set; }
            public string USER_STAMP { get; set; }
            public string PROCESS_STAMP { get; set; }
            public DateTime DATE_TIME_STAMP { get; set; }
      }

      
      
}
#pragma warning restore 1591